### ISSUE TITLE
Integration Tests for role

### ISSUE THREAD

**Issue by avalor1** [T-Systems-MMS/ansible-collection-letsencrypt#3]
Add Integration Tests as workflow for role.

Need to Test http- and dns-challenge certificate issuing for release process. 

**Required:**
- Test LE CA Server
  - to issue certificate
- DNS-01
  - DNS Server to create txt records
- HTTP-01
  - Webserver which serves hash files
    - Apache/Nginx Container

Could maybe all done via:
- https://github.com/letsencrypt/challtestsrv or
- https://github.com/letsencrypt/pebble

**Comment by rndmh3ro** [comment]
@avalor1 should we close this with https://github.com/T-Systems-MMS/ansible-collection-letsencrypt/pull/23?

**Comment by avalor1** [comment]
Yeah i think we can. For more specific tests for other providers i think we should open another issue.
