### ISSUE TITLE
subject_alt_name not optional

### ISSUE THREAD

**Issue by rndmh3ro** [T-Systems-MMS/ansible-collection-letsencrypt#9]
When creating a CSR I have to add a `subject_alt_name` even if I don't need one. This should be changed.

```
TASK [t_systems_mms.letsencrypt.letsencrypt : Create CSR for certificate] *****************************************************************************************************************************************
fatal: [localhost]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'subject_alt_name'

    The error appears to be in 'collections/ansible_collections/t_systems_mms/letsencrypt/roles/letsencrypt/tasks/dns-challenge.yml': line 2, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:

    ---
    - name: Create CSR for certificate
      ^ here

```

**Comment by jandd** [comment]
Using CNs instead of SubjectAlternativeNames is deprecated since 2000 (https://www.ietf.org/rfc/rfc2818.txt) therefore the requirement of a SubjectAlternativeName extension in CSRs is good practice. A possible solution in dns-challenge.yml would be to use the `'DNS:' + domain.common_name` value as default first subject_alt_name if domain.subject_alt_name is not defined

**Comment by avalor1** [comment]
Maybe we should completely remove the common name as a variable from the role. This wouldn't be a too critical change

As another workaround we could also add [use_common_name_for_san to the CSR creation task](https://docs.ansible.com/ansible/latest/collections/community/crypto/openssl_csr_module.html)
this would do the same thing as adding domain.common_name per default if SAN is not defined

**Comment by rndmh3ro** [comment]
> Maybe we should completely remove the common name as a variable from the role

Let's do this. As @jandd says, CommonName is deprecated and SAN should be used.
